### ISSUE TITLE
Marcin: przygotowanie projektu wyglądu aplikacji

### ISSUE THREAD

**Issue by einstein13** [einstein13/bogate_dokumentacja#11]
Zadanie nie powinno kolidować z zadaniem https://github.com/einstein13/bogate_dokumentacja/issues/6 , ale należy skontaktować się z Gosią w celu sprawdzenia stanu przygotowywanej dokumentacji.

Zadanie polega na stworzeniu pierwszej wizji graficznej aplikacji. Trzeba zastanowić się, jak mają wyglądać poszczególne funkcjonalności: ekran logowania, ekran wyszukiwania, prezentacji wyników, dodawania transakcji, prezentacji historii transakcji, inne jeśli coś zostało pominięte. Rysunki powinny być schematyczne (czyli wskazywać na umiejscowienie poszczególnych elementów, a nie ich kolorystykę).

**Comment by Marcin18** [comment]
Mam stworzony zakres ekranów aplikacji. Za chwilę prześle to na naszą skrzynkę w formie pdf. Troche mogłem wejść w zadanie #6

**Comment by einstein13** [comment]
Super! Jak na pierwszy model - świetnie. Menu z lewej, duże przyciski -> super!

Plik dołączam do dokumentacji.

Drobne uwagi: będzie nam ciężko utrzymać historię kursów walut, chyba, że przechowamy wyniki na urządzeniu mobilnym (jak to zrobić? - jeszcze nie wiem, ale się dowiem :P).

Również przedstawienie aktualnego stanu wszystkich kantorów i kursów, to może lepiej posłać ich do strony quantor.pl - my mamy api tylko na jedną walutę, więc musielibyśmy rzucić 3 osobne zapytania.

Ale to tylko moje dywagacje ;)
