### ISSUE TITLE
Marcin: Założenie wspólnego konta Phonegap

### ISSUE THREAD

**Issue by einstein13** [einstein13/bogate_dokumentacja#2]
Założenie wspólnego konta Phonegap oraz zalinkowanie projektu z bogate_kod. W pierwszym użyciu kod nie powinien działać.

Konto użytkownika i hasło należy wpisać jako wiadomości w naszej wspólnej skrzynce e-mail

**Comment by Marcin18** [comment]
Zadanie zostało wykonane, projekt założony, podpiety do Phonegapa, login i hasło zaraz będzie na skrzynce.
