### ISSUE TITLE
Gosia: Przygotowanie diagramu przypadków użycia

### ISSUE THREAD

**Issue by einstein13** [einstein13/bogate_dokumentacja#8]
Należy przygotować diagram przypadków użycia pod kątem umieszczenia go na forum jako część zaliczenia.

Przewidujemy aktorów:
Użytkownik, system logowania (zarówno nasza baza danych, jak i portale społecznościowe), źródła danych (NBP, quantor.pl)

Przewidujemy podstawowe funkcjonalności:
Logowanie użytkownika, znalezienie najlepszych cen, wprowadzenie nowej transakcji, pokazanie historii transakcji.

Podstawowe funkcjonalności należy rozwinąć (na schemacie) o wymagane zadania wewnętrzne.

Po zakończenie zadania, wszystkie wygenerowane pliki należy umieścić w folderze "diagram użycia" i poinformować zespół o zakończeniu zadania.

**Comment by 9osia** [comment]
Na utworzonym przeze mnie branchu mni znajdziecie pdf ze schematem przypadków użycia. 
Proszę zerknijcie czy jest ok, czy bardziej rozpisywać szczegóły.

**Comment by einstein13** [comment]
Wygląda super i jest dla mnie bardziej zrozumiałe niż ten pierwszy. Issue uważam za zamknięte. Następnym razem od razu dorzucaj do głównego brancha - po to jest kontrola wersji :) .
